"""
Named audit actions — use these strings in code so logs stay consistent for reporting.
"""


class AuditAction:
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    DEVICE_DELETED = "DEVICE_DELETED"
    EVENT_CREATED = "EVENT_CREATED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_RESOLVED = "EVENT_RESOLVED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNAUTHORIZED_ACCESS_ATTEMPT = "UNAUTHORIZED_ACCESS_ATTEMPT"
    ROLE_UPDATED = "ROLE_UPDATED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    INVALID_TOKEN = "INVALID_TOKEN"
    LOGIN_LOCKOUT = "LOGIN_LOCKOUT"
    ALERT_CREATED = "ALERT_CREATED"
    SUSPICIOUS_ACTIVITY_DETECTED = "SUSPICIOUS_ACTIVITY_DETECTED"
    BRUTE_FORCE_WARNING = "BRUTE_FORCE_WARNING"
